export type SqlDifficulty = "easy" | "medium" | "hard" | "extreme";
export type ContextLevel = "enough" | "medium" | "less" | "none";
export type SqlExpectation = "execute" | "clarify" | "unavailable";
export type ConversationalSqlCase = {
  id: string;
  difficulty: SqlDifficulty;
  context: ContextLevel;
  question: string;
  expectation: SqlExpectation;
  goldSql?: string;
  expectedAnswer?: string;
};

export const conversationalSqlCases: ConversationalSqlCase[] = [
  { id: "E01", difficulty: "easy", context: "enough", question: "Calculate total successfully paid revenue from the payments table, rounded to 2 decimals.", expectation: "execute", goldSql: "SELECT round(sum(amount), 2) AS paid_revenue FROM payments WHERE payment_status = 'paid'" },
  { id: "E02", difficulty: "easy", context: "medium", question: "How many customers are currently active?", expectation: "execute", goldSql: "SELECT count(*) AS active_customers FROM customers WHERE is_active" },
  { id: "E03", difficulty: "easy", context: "enough", question: "Count orders by status and list the statuses alphabetically.", expectation: "execute", goldSql: "SELECT status, count(*) AS orders FROM orders GROUP BY status ORDER BY status" },
  { id: "E04", difficulty: "easy", context: "medium", question: "Show the top 3 product categories by units sold, excluding cancelled orders.", expectation: "execute", goldSql: "SELECT p.category, sum(oi.quantity) AS units FROM order_items oi JOIN orders o USING (order_id) JOIN products p USING (product_id) WHERE o.status <> 'cancelled' GROUP BY p.category ORDER BY units DESC, p.category LIMIT 3" },
  { id: "E05", difficulty: "easy", context: "less", question: "Which region is best?", expectation: "clarify", expectedAnswer: "Ask what 'best' means, such as revenue, customers, order value, or support satisfaction." },
  { id: "E06", difficulty: "easy", context: "enough", question: "Calculate average successfully paid order value from payments, rounded to 2 decimals.", expectation: "execute", goldSql: "SELECT round(avg(amount), 2) AS average_paid_order_value FROM payments WHERE payment_status = 'paid'" },
  { id: "E07", difficulty: "easy", context: "none", question: "Calculate net profit after shipping costs and taxes.", expectation: "unavailable", expectedAnswer: "Shipping costs and taxes are not present, so net profit cannot be calculated from this database." },
  { id: "E08", difficulty: "easy", context: "enough", question: "What was successfully paid revenue in January 2025? Round to 2 decimals.", expectation: "execute", goldSql: "SELECT round(sum(p.amount), 2) AS january_revenue FROM payments p JOIN orders o USING (order_id) WHERE p.payment_status = 'paid' AND o.order_date >= DATE '2025-01-01' AND o.order_date < DATE '2025-02-01'" },
  { id: "E09", difficulty: "easy", context: "medium", question: "Count unresolved support tickets.", expectation: "execute", goldSql: "SELECT count(*) AS unresolved_tickets FROM support_tickets WHERE resolved_at IS NULL" },
  { id: "E10", difficulty: "easy", context: "less", question: "What is our most valuable product?", expectation: "clarify", expectedAnswer: "Ask whether value means revenue, units, gross margin, return rate, or another measure." },

  { id: "M01", difficulty: "medium", context: "enough", question: "Calculate successfully paid revenue by customer region, rounded to 2 decimals, highest first.", expectation: "execute", goldSql: "SELECT c.region, round(sum(p.amount), 2) AS revenue FROM payments p JOIN orders o USING (order_id) JOIN customers c USING (customer_id) WHERE p.payment_status = 'paid' GROUP BY c.region ORDER BY revenue DESC, c.region" },
  { id: "M02", difficulty: "medium", context: "medium", question: "Who are the top 5 customers by paid revenue? Return customer ID and revenue.", expectation: "execute", goldSql: "SELECT o.customer_id, round(sum(p.amount), 2) AS revenue FROM payments p JOIN orders o USING (order_id) WHERE p.payment_status = 'paid' GROUP BY o.customer_id ORDER BY revenue DESC, o.customer_id LIMIT 5" },
  { id: "M03", difficulty: "medium", context: "none", question: "Calculate website visitor-to-order conversion rate by campaign.", expectation: "unavailable", expectedAnswer: "Visitor or impression counts are absent, so visitor-to-order conversion cannot be calculated." },
  { id: "M04", difficulty: "medium", context: "enough", question: "Calculate attributed paid revenue divided by campaign spend for each campaign. Call it ROAS, round to 2 decimals, and rank highest first.", expectation: "execute", goldSql: "SELECT c.campaign_id, round(coalesce(sum(CASE WHEN p.payment_status = 'paid' THEN p.amount ELSE 0 END), 0) / nullif(c.spend, 0), 2) AS roas FROM campaigns c LEFT JOIN orders o USING (campaign_id) LEFT JOIN payments p USING (order_id) GROUP BY c.campaign_id, c.spend ORDER BY roas DESC, c.campaign_id" },
  { id: "M05", difficulty: "medium", context: "medium", question: "How many customers placed at least 2 completed orders?", expectation: "execute", goldSql: "SELECT count(*) AS repeat_customers FROM (SELECT customer_id FROM orders WHERE status = 'completed' GROUP BY customer_id HAVING count(*) >= 2) x" },
  { id: "M06", difficulty: "medium", context: "enough", question: "Calculate average support-ticket resolution hours by priority for resolved tickets, rounded to 1 decimal.", expectation: "execute", goldSql: "SELECT priority, round(avg(date_diff('minute', created_at, resolved_at)) / 60.0, 1) AS average_resolution_hours FROM support_tickets WHERE resolved_at IS NOT NULL GROUP BY priority ORDER BY priority" },
  { id: "M07", difficulty: "medium", context: "medium", question: "What percentage of non-cancelled orders were refunded? Round to 2 decimals.", expectation: "execute", goldSql: "SELECT round(100.0 * count(*) FILTER (WHERE status = 'refunded') / nullif(count(*), 0), 2) AS refund_rate_pct FROM orders WHERE status <> 'cancelled'" },
  { id: "M08", difficulty: "medium", context: "enough", question: "Calculate gross merchandise margin dollars by product category for completed orders using quantity times discounted unit price minus quantity times unit cost. Round to 2 decimals.", expectation: "execute", goldSql: "SELECT p.category, round(sum(oi.quantity * oi.unit_price * (1 - oi.discount_pct) - oi.quantity * p.unit_cost), 2) AS gross_margin FROM order_items oi JOIN orders o USING (order_id) JOIN products p USING (product_id) WHERE o.status = 'completed' GROUP BY p.category ORDER BY gross_margin DESC, p.category" },
  { id: "M09", difficulty: "medium", context: "medium", question: "Calculate paid revenue growth from January to February 2025 as a percentage, rounded to 2 decimals.", expectation: "execute", goldSql: "WITH monthly AS (SELECT date_trunc('month', o.order_date) AS month, sum(p.amount) AS revenue FROM payments p JOIN orders o USING (order_id) WHERE p.payment_status = 'paid' AND o.order_date >= DATE '2025-01-01' AND o.order_date < DATE '2025-03-01' GROUP BY 1) SELECT round(100.0 * (max(revenue) FILTER (WHERE month = DATE '2025-02-01') - max(revenue) FILTER (WHERE month = DATE '2025-01-01')) / nullif(max(revenue) FILTER (WHERE month = DATE '2025-01-01'), 0), 2) AS growth_pct FROM monthly" },
  { id: "M10", difficulty: "medium", context: "enough", question: "Calculate average successfully paid order value by customer segment, rounded to 2 decimals.", expectation: "execute", goldSql: "SELECT c.segment, round(avg(p.amount), 2) AS average_order_value FROM payments p JOIN orders o USING (order_id) JOIN customers c USING (customer_id) WHERE p.payment_status = 'paid' GROUP BY c.segment ORDER BY c.segment" },
  { id: "M11", difficulty: "medium", context: "less", question: "Which acquisition channel works best?", expectation: "clarify", expectedAnswer: "Ask whether success means paid revenue, active customers, repeat purchase, support outcomes, or another metric." },
  { id: "M12", difficulty: "medium", context: "none", question: "Why did customers request refunds?", expectation: "unavailable", expectedAnswer: "The database records refund status but no refund reason, so the cause cannot be determined." },
  { id: "M13", difficulty: "medium", context: "enough", question: "Calculate average item quantity per non-cancelled order, rounded to 2 decimals.", expectation: "execute", goldSql: "SELECT round(avg(item_quantity), 2) AS average_items_per_order FROM (SELECT o.order_id, sum(oi.quantity) AS item_quantity FROM orders o JOIN order_items oi USING (order_id) WHERE o.status <> 'cancelled' GROUP BY o.order_id) x" },
  { id: "M14", difficulty: "medium", context: "medium", question: "List product IDs that were never included in an order.", expectation: "execute", goldSql: "SELECT p.product_id FROM products p LEFT JOIN order_items oi USING (product_id) WHERE oi.product_id IS NULL ORDER BY p.product_id" },
  { id: "M15", difficulty: "medium", context: "less", question: "Is this a healthy business?", expectation: "clarify", expectedAnswer: "Ask which health criteria and period matter, such as growth, margin, refunds, retention, cash flow, or targets." },

  { id: "H01", difficulty: "hard", context: "enough", question: "For each customer signup month, calculate paid revenue generated within 90 days after each customer's signup date. Round to 2 decimals.", expectation: "execute", goldSql: "SELECT date_trunc('month', c.signup_date) AS signup_month, round(sum(p.amount), 2) AS revenue_90d FROM customers c JOIN orders o USING (customer_id) JOIN payments p USING (order_id) WHERE p.payment_status = 'paid' AND o.order_date >= c.signup_date AND o.order_date < c.signup_date + INTERVAL '90 days' GROUP BY 1 ORDER BY 1" },
  { id: "H02", difficulty: "hard", context: "none", question: "Calculate the causal incremental revenue lift created by each campaign.", expectation: "unavailable", expectedAnswer: "Causal lift requires a control or counterfactual design; attributed orders alone cannot establish incremental impact." },
  { id: "H03", difficulty: "hard", context: "enough", question: "Rank the top 5 customers by completed-order gross margin: discounted line revenue minus product cost. Return customer ID and margin rounded to 2 decimals.", expectation: "execute", goldSql: "SELECT o.customer_id, round(sum(oi.quantity * oi.unit_price * (1 - oi.discount_pct) - oi.quantity * p.unit_cost), 2) AS gross_margin FROM orders o JOIN order_items oi USING (order_id) JOIN products p USING (product_id) WHERE o.status = 'completed' GROUP BY o.customer_id ORDER BY gross_margin DESC, o.customer_id LIMIT 5" },
  { id: "H04", difficulty: "hard", context: "enough", question: "Calculate monthly paid revenue and its trailing 3-month rolling average for 2025, rounded to 2 decimals.", expectation: "execute", goldSql: "WITH monthly AS (SELECT date_trunc('month', o.order_date) AS month, sum(p.amount) AS revenue FROM payments p JOIN orders o USING (order_id) WHERE p.payment_status = 'paid' GROUP BY 1) SELECT month, round(revenue, 2) AS revenue, round(avg(revenue) OVER (ORDER BY month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 2) AS rolling_3m FROM monthly ORDER BY month" },
  { id: "H05", difficulty: "hard", context: "medium", question: "Calculate the correlation across customers between support-ticket count and refunded-order count, rounded to 3 decimals.", expectation: "execute", goldSql: "WITH t AS (SELECT customer_id, count(*) AS tickets FROM support_tickets GROUP BY customer_id), r AS (SELECT customer_id, count(*) FILTER (WHERE status = 'refunded') AS refunds FROM orders GROUP BY customer_id) SELECT round(corr(coalesce(t.tickets, 0), coalesce(r.refunds, 0)), 3) AS correlation FROM customers c LEFT JOIN t USING (customer_id) LEFT JOIN r USING (customer_id)" },
  { id: "H06", difficulty: "hard", context: "less", question: "Did campaign 4 perform significantly better?", expectation: "clarify", expectedAnswer: "Ask which outcome, comparison group, period, and statistical significance method define 'better'." },
  { id: "H07", difficulty: "hard", context: "medium", question: "Calculate median successfully paid order value by customer region, rounded to 2 decimals.", expectation: "execute", goldSql: "SELECT c.region, round(median(p.amount), 2) AS median_order_value FROM payments p JOIN orders o USING (order_id) JOIN customers c USING (customer_id) WHERE p.payment_status = 'paid' GROUP BY c.region ORDER BY c.region" },
  { id: "H08", difficulty: "hard", context: "enough", question: "Calculate returned units as a percentage of non-cancelled units sold by product category, rounded to 2 decimals.", expectation: "execute", goldSql: "WITH sold AS (SELECT p.category, sum(oi.quantity) AS units FROM order_items oi JOIN orders o USING (order_id) JOIN products p USING (product_id) WHERE o.status <> 'cancelled' GROUP BY p.category), returned AS (SELECT p.category, sum(r.return_quantity) AS units FROM returns r JOIN order_items oi USING (order_item_id) JOIN products p USING (product_id) GROUP BY p.category) SELECT s.category, round(100.0 * coalesce(r.units, 0) / nullif(s.units, 0), 2) AS return_rate_pct FROM sold s LEFT JOIN returned r USING (category) ORDER BY return_rate_pct DESC, s.category" },
  { id: "H09", difficulty: "hard", context: "enough", question: "For each campaign, calculate spend divided by distinct customers whose first-ever order occurred during that campaign's date range and was attributed to it. Round to 2 decimals.", expectation: "execute", goldSql: "WITH first_orders AS (SELECT customer_id, min(order_date) AS first_date FROM orders GROUP BY customer_id), acquired AS (SELECT c.campaign_id, count(DISTINCT o.customer_id) AS customers FROM campaigns c LEFT JOIN orders o ON o.campaign_id = c.campaign_id AND o.order_date BETWEEN c.start_date AND c.end_date LEFT JOIN first_orders f ON f.customer_id = o.customer_id AND f.first_date = o.order_date GROUP BY c.campaign_id) SELECT c.campaign_id, round(c.spend / nullif(a.customers, 0), 2) AS acquisition_cost FROM campaigns c JOIN acquired a USING (campaign_id) ORDER BY c.campaign_id" },
  { id: "H10", difficulty: "hard", context: "medium", question: "Calculate the 90th percentile of successfully paid order amount, rounded to 2 decimals.", expectation: "execute", goldSql: "SELECT round(quantile_cont(amount, 0.9), 2) AS p90_paid_order FROM payments WHERE payment_status = 'paid'" },
  { id: "H11", difficulty: "hard", context: "medium", question: "Calculate average days from customer signup to first order by acquisition channel, rounded to 1 decimal.", expectation: "execute", goldSql: "WITH first_orders AS (SELECT customer_id, min(order_date) AS first_order_date FROM orders GROUP BY customer_id) SELECT c.acquisition_channel, round(avg(date_diff('day', c.signup_date, f.first_order_date)), 1) AS average_days_to_first_order FROM customers c JOIN first_orders f USING (customer_id) GROUP BY c.acquisition_channel ORDER BY c.acquisition_channel" },
  { id: "H12", difficulty: "hard", context: "less", question: "Calculate customer churn rate.", expectation: "clarify", expectedAnswer: "Ask for a churn definition, eligibility population, observation window, and cutoff date." },
  { id: "H13", difficulty: "hard", context: "enough", question: "What percentage of paid revenue comes from the top 10 percent of customers by paid revenue? Round to 2 decimals.", expectation: "execute", goldSql: "WITH customer_revenue AS (SELECT o.customer_id, sum(p.amount) AS revenue FROM payments p JOIN orders o USING (order_id) WHERE p.payment_status = 'paid' GROUP BY o.customer_id), ranked AS (SELECT *, row_number() OVER (ORDER BY revenue DESC) AS rank, count(*) OVER () AS customers FROM customer_revenue) SELECT round(100.0 * sum(revenue) FILTER (WHERE rank <= ceil(customers * 0.1)) / sum(revenue), 2) AS top_10_pct_revenue_share FROM ranked" },
  { id: "H14", difficulty: "hard", context: "medium", question: "Calculate payment failure rate by payment method, rounded to 2 decimals.", expectation: "unavailable", expectedAnswer: "The payments table has paid and refunded outcomes but no failed-payment records, so failure rate cannot be measured." },
  { id: "H15", difficulty: "hard", context: "none", question: "Calculate first-touch and last-touch campaign attribution revenue.", expectation: "unavailable", expectedAnswer: "Only one campaign ID is stored per order and no touchpoint history exists, so first- and last-touch attribution cannot be reconstructed." },
  { id: "H16", difficulty: "hard", context: "enough", question: "Count customers who bought at least one Electronics product but never bought a Home product in a non-cancelled order.", expectation: "execute", goldSql: "WITH bought AS (SELECT DISTINCT o.customer_id, p.category FROM orders o JOIN order_items oi USING (order_id) JOIN products p USING (product_id) WHERE o.status <> 'cancelled') SELECT count(*) AS customers FROM (SELECT customer_id FROM bought GROUP BY customer_id HAVING bool_or(category = 'Electronics') AND NOT bool_or(category = 'Home')) x" },
  { id: "H17", difficulty: "hard", context: "medium", question: "For each first-purchase month, calculate the percentage of customers who placed another order in the following calendar month, rounded to 2 decimals.", expectation: "execute", goldSql: "WITH firsts AS (SELECT customer_id, date_trunc('month', min(order_date)) AS cohort_month FROM orders GROUP BY customer_id), retained AS (SELECT f.customer_id, f.cohort_month, bool_or(date_trunc('month', o.order_date) = f.cohort_month + INTERVAL '1 month') AS retained FROM firsts f LEFT JOIN orders o USING (customer_id) GROUP BY f.customer_id, f.cohort_month) SELECT cohort_month, round(100.0 * count(*) FILTER (WHERE retained) / count(*), 2) AS next_month_retention_pct FROM retained GROUP BY cohort_month ORDER BY cohort_month" },
  { id: "H18", difficulty: "hard", context: "less", question: "Which customer segments are statistically different?", expectation: "clarify", expectedAnswer: "Ask which outcome, test, confidence level, and comparison design should define a statistical difference." },
  { id: "H19", difficulty: "hard", context: "none", question: "What caused the West region's revenue decline?", expectation: "unavailable", expectedAnswer: "No comparison period is specified and observational tables cannot establish cause; request the period and investigate candidate drivers without causal claims." },
  { id: "H20", difficulty: "hard", context: "enough", question: "Audit join coverage: count orders without customers and order items without matching orders or products.", expectation: "execute", goldSql: "SELECT (SELECT count(*) FROM orders o LEFT JOIN customers c USING (customer_id) WHERE c.customer_id IS NULL) AS orders_without_customers, (SELECT count(*) FROM order_items oi LEFT JOIN orders o USING (order_id) WHERE o.order_id IS NULL) AS items_without_orders, (SELECT count(*) FROM order_items oi LEFT JOIN products p USING (product_id) WHERE p.product_id IS NULL) AS items_without_products" },

  { id: "X01", difficulty: "extreme", context: "enough", question: "Find the product category with the largest absolute difference between its completed-order gross-margin percentage and the overall completed-order gross-margin percentage. Return the category and percentage-point difference, rounded to 2 decimals.", expectation: "execute", goldSql: "WITH category AS (SELECT p.category, sum(oi.quantity * oi.unit_price * (1 - oi.discount_pct) - oi.quantity * p.unit_cost) / nullif(sum(oi.quantity * oi.unit_price * (1 - oi.discount_pct)), 0) * 100 AS margin_pct FROM orders o JOIN order_items oi USING (order_id) JOIN products p USING (product_id) WHERE o.status = 'completed' GROUP BY p.category), overall AS (SELECT sum(oi.quantity * oi.unit_price * (1 - oi.discount_pct) - oi.quantity * p.unit_cost) / nullif(sum(oi.quantity * oi.unit_price * (1 - oi.discount_pct)), 0) * 100 AS margin_pct FROM orders o JOIN order_items oi USING (order_id) JOIN products p USING (product_id) WHERE o.status = 'completed') SELECT category, round(abs(category.margin_pct - overall.margin_pct), 2) AS percentage_point_difference FROM category CROSS JOIN overall ORDER BY percentage_point_difference DESC, category LIMIT 1" },
  { id: "X02", difficulty: "extreme", context: "medium", question: "Calculate the optimal campaign budget reallocation that maximizes next-quarter incremental revenue.", expectation: "unavailable", expectedAnswer: "Historical attributed revenue does not provide a causal response curve or future constraints, so an optimal incremental budget allocation cannot be calculated." },
  { id: "X03", difficulty: "extreme", context: "less", question: "Forecast next quarter's revenue.", expectation: "clarify", expectedAnswer: "Ask for forecast horizon, method, seasonality assumptions, uncertainty requirements, and whether the single observed year is sufficient." },
  { id: "X04", difficulty: "extreme", context: "none", question: "Calculate the causal effect of support satisfaction on customer retention.", expectation: "unavailable", expectedAnswer: "The observational data, missing treatment design, and undefined retention measure cannot identify a causal effect." },
  { id: "X05", difficulty: "extreme", context: "enough", question: "For monthly paid revenue by product category, calculate a within-category z-score using all 2025 months and return the 3 category-month combinations with the largest absolute z-score. Round revenue and z-score to 2 decimals.", expectation: "execute", goldSql: "WITH monthly AS (SELECT p.category, date_trunc('month', o.order_date) AS month, sum(oi.quantity * oi.unit_price * (1 - oi.discount_pct)) AS revenue FROM orders o JOIN payments pay USING (order_id) JOIN order_items oi USING (order_id) JOIN products p USING (product_id) WHERE pay.payment_status = 'paid' GROUP BY p.category, month), scored AS (SELECT category, month, revenue, (revenue - avg(revenue) OVER (PARTITION BY category)) / nullif(stddev_samp(revenue) OVER (PARTITION BY category), 0) AS z_score FROM monthly) SELECT category, month, round(revenue, 2) AS revenue, round(z_score, 2) AS z_score FROM scored ORDER BY abs(z_score) DESC, category, month LIMIT 3" },
];
