import { runAnalyticalHoldout, type AnalyticalHoldoutDefinition } from "./analytical-holdout-runner.ts";

const definition: AnalyticalHoldoutDefinition = {
  suite: "analytical-holdout-v4",
  frozenAt: "2026-08-04",
  databaseName: "analytical-holdout-v4.duckdb",
  setupSql: `
    CREATE TABLE telescopes AS SELECT i::INTEGER AS telescope_id, CASE i % 3 WHEN 0 THEN 'Mountain' WHEN 1 THEN 'Desert' ELSE 'Island' END AS site, (i % 4 <> 0) AS active FROM range(1, 10) t(i);
    CREATE TABLE targets AS SELECT i::INTEGER AS target_id, CASE i % 4 WHEN 0 THEN 'Galaxy' WHEN 1 THEN 'Nebula' WHEN 2 THEN 'Star' ELSE 'Comet' END AS object_type, CASE i % 3 WHEN 0 THEN 'Orion' WHEN 1 THEN 'Lyra' ELSE 'Draco' END AS constellation FROM range(1, 19) t(i);
    CREATE TABLE observations AS SELECT i::INTEGER AS observation_id, ((i * 5) % 9 + 1)::INTEGER AS telescope_id, ((i * 7) % 18 + 1)::INTEGER AS target_id, DATE '2026-01-01' + ((i * 3) % 59)::INTEGER AS observed_on, (30 + i % 240)::DOUBLE AS exposure_seconds, (5 + i % 70)::DOUBLE AS signal_strength, CASE i % 3 WHEN 0 THEN 'High' WHEN 1 THEN 'Medium' ELSE 'Low' END AS quality FROM range(1, 121) t(i);
    CREATE TABLE calibrations AS SELECT i::INTEGER AS calibration_id, ((i * 4) % 8 + 1)::INTEGER AS telescope_id, TIMESTAMP '2026-01-01 06:00:00' + i * INTERVAL '2 days' AS calibrated_at FROM range(1, 25) t(i);
    CREATE TABLE observation_runs AS SELECT i::INTEGER AS run_id, ((i * 7) % 9 + 1)::INTEGER AS telescope_id, TIMESTAMP '2026-01-01 19:00:00' + i * INTERVAL '17 hours' AS opened_at, TIMESTAMP '2026-01-01 19:00:00' + i * INTERVAL '17 hours' + (20 + i % 100) * INTERVAL '1 minute' AS closed_at FROM range(1, 46) t(i);
  `,
  cases: [
    { id: "astro-01", question: "What is the average number of observations per telescope?", goldSql: "SELECT AVG(metric_value) FROM (SELECT telescope_id, COUNT(DISTINCT observation_id) AS metric_value FROM observations GROUP BY telescope_id) q", expectedPlan: { operation: "aggregate_over_groups", source: "observations", metric: "observations.observation_id", groupField: "observations.telescope_id", innerAggregate: "count", outerAggregate: "avg", distinct: true } },
    { id: "astro-02", question: "What is the average total exposure seconds per target?", goldSql: "SELECT AVG(metric_value) FROM (SELECT target_id, SUM(exposure_seconds) AS metric_value FROM observations GROUP BY target_id) q", expectedPlan: { operation: "per_entity_average", source: "observations", metric: "observations.exposure_seconds", entity: "observations.target_id" } },
    { id: "astro-03", question: "How many distinct telescopes recorded Galaxy observations?", goldSql: "SELECT COUNT(DISTINCT telescope_id) FROM observations JOIN targets USING (target_id) WHERE object_type = 'Galaxy'", expectedPlan: { operation: "distinct_count", source: "observations", entity: "observations.telescope_id", filters: [{ column: "targets.object_type", operator: "eq", value: "Galaxy" }] } },
    { id: "astro-04", question: "What is the average duration between opened at and closed at in hours?", goldSql: "SELECT AVG(DATE_DIFF('minute', opened_at, closed_at)) / 60.0 FROM observation_runs", expectedPlan: { operation: "duration_average", source: "observation_runs", startField: "observation_runs.opened_at", endField: "observation_runs.closed_at" } },
    { id: "astro-05", question: "What is the ratio of total signal strength divided by total observations?", goldSql: "SELECT SUM(signal_strength) / NULLIF(COUNT(*), 0) FROM observations", expectedPlan: { operation: "ratio", source: "observations", metric: "observations.signal_strength", secondaryMetric: "*" } },
    { id: "astro-06", question: "How many telescopes have at least 5 observations?", goldSql: "SELECT COUNT(*) FROM (SELECT telescope_id FROM observations GROUP BY telescope_id HAVING COUNT(*) >= 5) q", expectedPlan: { operation: "threshold_count", source: "observations", entity: "observations.telescope_id", threshold: 5 } },
    { id: "astro-07", question: "Which telescopes were never linked to calibrations?", goldSql: "SELECT telescope_id FROM telescopes LEFT JOIN calibrations USING (telescope_id) WHERE calibration_id IS NULL ORDER BY telescope_id", expectedPlan: { operation: "anti_join", source: "telescopes", entity: "telescopes.telescope_id", relatedField: "calibrations.calibration_id" } },
    { id: "astro-08", question: "What was the growth in total exposure seconds using observed on from January 2026 to February 2026?", goldSql: "WITH p AS (SELECT SUM(exposure_seconds) FILTER (WHERE observed_on >= DATE '2026-01-01' AND observed_on < DATE '2026-02-01') a, SUM(exposure_seconds) FILTER (WHERE observed_on >= DATE '2026-02-01' AND observed_on < DATE '2026-03-01') b FROM observations) SELECT 100.0 * (b-a) / NULLIF(a,0) FROM p", expectedPlan: { operation: "period_growth", source: "observations", metric: "observations.exposure_seconds", dateField: "observations.observed_on", firstStart: "2026-01-01", firstEnd: "2026-02-01", secondStart: "2026-02-01", secondEnd: "2026-03-01" } },
    { id: "astro-09", question: "What is the average number of distinct targets per telescope?", goldSql: "SELECT AVG(metric_value) FROM (SELECT telescope_id, COUNT(DISTINCT target_id) AS metric_value FROM observations GROUP BY telescope_id) q", expectedPlan: { operation: "aggregate_over_groups", source: "observations", metric: "observations.target_id", groupField: "observations.telescope_id", innerAggregate: "count", outerAggregate: "avg", distinct: true } },
    { id: "astro-10", question: "What is the ratio of total exposure seconds divided by total signal strength?", goldSql: "SELECT SUM(exposure_seconds) / NULLIF(SUM(signal_strength), 0) FROM observations", expectedPlan: { operation: "ratio", source: "observations", metric: "observations.exposure_seconds", secondaryMetric: "observations.signal_strength" } },
    { id: "astro-11", question: "What percentage of observations have High quality?", goldSql: "SELECT 100.0 * COUNT(*) FILTER (WHERE quality = 'High') / NULLIF(COUNT(*), 0) FROM observations", expectedPlan: { operation: "conditional_rate", source: "observations", numeratorFilters: [{ column: "observations.quality", operator: "eq", value: "High" }], denominatorFilters: [] } },
    { id: "astro-12", question: "Which telescope is best?", boundary: "clarify" },
  ],
};

await runAnalyticalHoldout(definition);
