import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { masteryProgress, validateMasteryTree, type MasteryTree } from "../lib/mastery-tree.ts";

const sourcePath = resolve(process.cwd(), "content", "path-to-mastery.json");
const outputPath = resolve(process.cwd(), "docs", "PATH_TO_MASTERY.md");
const tree: unknown = JSON.parse(readFileSync(sourcePath, "utf8"));
validateMasteryTree(tree);
const progress = masteryProgress(tree);

const status = (value: string) => value.replaceAll("-", " ").replace(/\b\w/g, (character) => character.toUpperCase());
const sections = tree.branches.map((branch) => `## ${branch.glyph} ${branch.name} — ${branch.score.toFixed(1)}/5

${branch.summary}

| Skill | State | Score | Next backlog item |
|---|---:|---:|---|
${branch.nodes.map((node) => `| [${node.name}](#${node.id}) | ${status(node.status)} | ${node.score.toFixed(1)}/5 | ${node.backlog} |`).join("\n")}

${branch.nodes.map((node) => `<a id="${node.id}"></a>
### ${node.name}

${node.description}

- **State:** ${status(node.status)}
- **Dependencies:** ${node.dependencies.length ? node.dependencies.join(", ") : "Foundation node"}
- **Unlock requirements:** ${node.acceptance.join("; ")}
- **Verified evidence:** ${node.evidence.length ? node.evidence.join("; ") : "None yet"}
- **Next:** ${node.backlog}`).join("\n\n")}`).join("\n\n");

const markdown = `# ${tree.title}

> Generated from [content/path-to-mastery.json](../content/path-to-mastery.json). Do not edit this file by hand.

**Verified:** ${tree.updatedAt} · **Overall progress:** ${progress.percent}% · **Unlocked:** ${progress.unlocked}/${progress.total} · **Training:** ${progress.active}

${tree.vision}

## How mastery works

- **Vision:** proposed final capability.
- **Locked:** prerequisite work is missing.
- **Ready:** approved and available to implement.
- **In progress:** an implementation branch or pull request exists.
- **Training:** shipped, but below its strict quality threshold.
- **Unlocked:** merged and every acceptance criterion passes.
- **Mastered:** quality has remained high through broader validation.
- **Regressed:** a previously passing skill fell below its threshold.

This is both the public capability tree and the contributor backlog. A merged feature does not unlock automatically, and private vault data or evaluation answers must never be published as evidence.

${sections}
`;

if (process.argv.includes("--check")) {
  if (readFileSync(outputPath, "utf8") !== markdown) throw new Error("docs/PATH_TO_MASTERY.md is stale. Run npm run mastery:generate.");
} else {
  writeFileSync(outputPath, markdown);
  console.log(`Generated ${outputPath} from ${sourcePath}`);
}
