import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { materializeMasteryTree, masteryProgress, validateMasteryTree, type MasteryEvidenceRegistry } from "../lib/mastery-tree.ts";
import { normalizeLineEndings } from "../lib/text-normalization.ts";
import { validateMasteryContributors } from "../lib/mastery-contributors.ts";

const readJson = (name: string): unknown => JSON.parse(readFileSync(resolve(process.cwd(), "content", name), "utf8"));
const source: unknown = readJson("path-to-mastery.json");
const evidenceValue: unknown = readJson("mastery-evidence.json");
validateMasteryTree(source, evidenceValue);
const evidence = evidenceValue as MasteryEvidenceRegistry;
const tree = materializeMasteryTree(source);
const contributors: unknown = readJson("mastery-contributors.json");
validateMasteryContributors(contributors, tree, evidence);
const progress = masteryProgress(tree);
const evidenceById = new Map(evidence.entries.map((entry) => [entry.id, entry]));
const claimCount = contributors.contributors.reduce((total, contributor) => total + contributor.claims.length, 0);
const outputPath = resolve(process.cwd(), "docs", "PATH_TO_MASTERY.md");

const label = (value: string) => value.replaceAll("-", " ").replace(/\b\w/g, (character) => character.toUpperCase());
const cite = (id: string) => { const item = evidenceById.get(id); return item ? `[${item.reference}](${item.url})` : id; };
const sections = tree.epics.map((epic) => `## ${epic.glyph} ${epic.name} — ${epic.progressPercent}%

${epic.summary}

| Capability | Derived state | Criteria verified | Derived score | Next work |
|---|---:|---:|---:|---|
${epic.nodes.map((node) => `| [${node.name}](#${node.id}) | ${label(node.status)} | ${node.verifiedCriteria}/${node.totalCriteria} | ${node.score.toFixed(1)}/5 | ${node.backlog} |`).join("\n")}

${epic.nodes.map((node) => `<a id="${node.id}"></a>
### ${node.name}

${node.description}

- **Derived state:** ${label(node.status)}
- **Derived score:** ${node.score.toFixed(1)}/5
- **Dependencies:** ${node.dependencies.length ? node.dependencies.join(", ") : "Foundation node"}
- **Next:** ${node.backlog}

| Acceptance criterion | Assessment | Merged evidence | Audit note |
|---|---:|---|---|
${node.criteria.map((criterion) => `| ${criterion.text} | ${label(criterion.state)} | ${criterion.evidence.length ? criterion.evidence.map(cite).join(" ") : "None"} | ${criterion.note ?? "—"} |`).join("\n")}`).join("\n\n")}`).join("\n\n");

const markdown = `# ${tree.title}

> Generated from the governed [Rangabot charter](RANGABOT_CHARTER.md), [program map](../content/path-to-mastery.json), [merged evidence registry](../content/mastery-evidence.json), and [contributor registry](../content/mastery-contributors.json). Scores and states are calculated; do not edit this file by hand.

**Capability readiness:** ${progress.readinessPercent}% (${progress.unlocked}/${progress.total} fully unlocked) · **Criterion verification:** ${progress.verificationPercent}% (${progress.criteriaVerified}/${progress.criteriaTotal}) · **Weighted development progress:** ${progress.developmentPercent}% · **Below gate:** ${progress.active} · **Evidence checked:** ${tree.evidenceVerifiedAt}

${tree.vision}

## Strict scoring method

- Every node is a program capability; every checklist row is an independently assessed acceptance criterion.
- Verified = 1 point, partial = 0.5, planned or failed = 0. Node and epic scores are calculated from those points.
- Capability readiness is the primary product metric and counts only fully unlocked or mastered capabilities. Weighted development progress is secondary and includes half-credit for partial work.
- Unlocked requires every criterion to be verified. A failed criterion keeps a capability below gate; a failure on a formerly unlocked node marks it regressed.
- A merged PR proves that work landed, not that its quality gate passed. Verification requires the PR plus the test, audit, or observable behavior named by the criterion.
- Private evaluation answers, chats, memories, and Knowledge Vault files are never published as evidence.

## Contributor achievements

**Recognized contributors:** ${contributors.contributors.length} · **Merged, attributable node claims:** ${claimCount}

Achievement credit is separate from readiness. It recognizes authored merged work and remains even when a capability is partial or regressed. Official changes require opt-in consent, attributable evidence, the **mastery-approved** label, and CODEOWNER review.

${sections}
`;

if (process.argv.includes("--check")) {
  if (normalizeLineEndings(readFileSync(outputPath, "utf8")) !== normalizeLineEndings(markdown)) throw new Error("docs/PATH_TO_MASTERY.md is stale. Run npm run mastery:generate.");
} else {
  writeFileSync(outputPath, markdown);
  console.log(`Generated ${outputPath}`);
}
